/// Flutter icons SocApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SocApp
///      fonts:
///       - asset: fonts/SocApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SocApp {
  SocApp._();

  static const _kFontFam = 'SocApp';

  static const IconData tab_icon_discover = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData tab_icon_cahat = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData tab_icon_fill = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData tab_icon_shape = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData tab_icon_face = const IconData(0xe805, fontFamily: _kFontFam);
}
